[package]
name = "contracts"
edition = { workspace = true }
rust-version = "1.81"

[lib]
path = "metadata.rs"

[dependencies]
sdk = { workspace = true }
contract1 = { workspace = true, features = ["client"] }
# contract2 removed - replaced with Noir identity verification

[build-dependencies]
risc0-build = { version = "2.0.2", optional = true }

[package.metadata.risc0]
methods = ["contract1"]

[features]
build = ["dep:risc0-build"]
nonreproducible = ["build", "all"]

# Following features are used to choose which contracts should be rebuild with docker
all = ["contract1"]
contract1 = []
# contract2 feature removed
